name: master_instrument
version: 1.0
config-version: 2
profile: staging_profile

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  master_instrument:
    referential:
      +schema: referential
      +materialized: incremental
    staging:
      +schema: staging
      +materialized: view