FROM python:3.12-slim


RUN pip install --no-cache-dir uv

WORKDIR /opt/dagster/app

COPY ./pyproject.toml ./uv.lock* ./


RUN if [ -f "uv.lock" ]; then \
        uv export --format requirements-txt --no-dev > requirements.txt && \
        uv pip install --system -r requirements.txt; \
    else \
        uv pip install --system -e .; \
    fi


ENV PYTHONPATH=/opt/dagster/app


COPY ./master_instrument ./master_instrument
COPY ./alembic ./alembic
COPY ./config ./config
COPY ./sling ./sling
COPY ./dbt_project ./dbt_project

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "master_instrument.etl.definitions"]