FROM python:3.12-slim

# Install uv
RUN pip install --no-cache-dir uv

# Create DAGSTER_HOME
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME

# Set working directory
WORKDIR $DAGSTER_HOME

# Copy dependency files
COPY ./pyproject.toml ./uv.lock* ./

# Installer juste Dagster
RUN if [ -f "uv.lock" ]; then \
        uv export --format requirements-txt --no-dev > requirements.txt && \
        uv pip install --system -r requirements.txt; \
    else \
        uv pip install --system -e .; \
    fi

# Copier .env pour les variables Dagster
COPY .env* ./

# Copier les fichiers de config Dagster
COPY dagster_home/dagster.yaml $DAGSTER_HOME/
COPY dagster_home/workspace.yaml $DAGSTER_HOME/