# config/sling/referential/refinitive_replications.yaml
source: QA_MSSQL
target: REFERENTIAL_POSTGRES

defaults:
  mode: full-refresh
  object: raw.qa_{stream_table}
  schema: raw

streams:
  dbo.DS2Company:
    meta:
      dagster:
        asset_key: raw.qa_ds2company
        group: "refinitiv_qa"
  dbo.DS2Security:
    meta:
      dagster:
        asset_key: raw.qa_ds2security
        group: "refinitiv_qa"
  dbo.DS2CtryQtInfo:
    sql: |
      SELECT
        *
      FROM dbo.DS2CtryQtInfo QT
      JOIN vw_SecurityMappingX X
        ON X.vencode = QT.InfoCode
        AND X.ventype = 33 AND X.rank = 1
        AND X.StartDate = (
        SELECT MAX(I.StartDate)
        FROM vw_SecurityMappingX AS I
        WHERE I.typ = X.typ AND I.vencode = X.vencode AND I.ventype = X.ventype
        )
    meta:
      dagster:
        asset_key: raw.qa_ds2ctryqtinfo
        group: "refinitiv_qa"
  dbo.RKDFndCmpRefIssue:
    sql: |
      SELECT
        *
      FROM RKDFndCmpRefIssue R
      JOIN vw_SecurityMappingX X
        ON X.vencode = R.IssueCode
        AND X.ventype = 26
        AND X.rank = 1
        AND X.StartDate = (
        SELECT MAX(I.StartDate)
        FROM vw_SecurityMappingX AS I
        WHERE I.typ = X.typ AND I.vencode = X.vencode AND I.ventype = X.ventype
        )

    meta:
      dagster:
        asset_key: raw.qa_rkdfndcmprefissue
        group: "refinitiv_qa"
  dbo.RKDFndCmpFiling:
    meta:
      dagster:
        asset_key: raw.qa_rkdfndcmpfiling
        group: "refinitiv_qa"
  dbo.RKDFndCmpDet:
    meta:
      dagster:
        asset_key: raw.qa_rkdfndcmpdet
        group: "refinitiv_qa"     
  dbo.RKDFndCmpRef:
    meta:
      dagster:
        asset_key: raw.qa_rkdfndcmpref
        group: "refinitiv_qa"  
  dbo.RKDFndCmpWebLink:
    meta:
      dagster:
        asset_key: raw.qa_rkdfndcmpweblink
        group: "refinitiv_qa"  
  dbo.DS2Exchange:
    meta:
      dagster:
        asset_key: raw.qa_ds2exchange
        group: "refinitiv_qa"
  dbo.DS2ExchQtInfo:
    meta:
      dagster:
        asset_key: raw.qa_ds2exchqtinfo
        group: "refinitiv_qa"
  dbo.DS2XRef:
    meta:
      dagster:
        asset_key: raw.qa_ds2xref
        group: "refinitiv_qa"
  dbo.RKDFndCode:
    meta:
      dagster:
        asset_key: raw.qa_rkdfndcode
        group: "refinitiv_qa"
  dbo.vw_IBES2Mapping:
    sql: |
      SELECT * FROM dbo.vw_IBES2Mapping
    meta:
      dagster:
        asset_key: raw.qa_vw_ibes2mapping
        group: "refinitiv_qa"