source: QA_MSSQL
target: REFERENTIAL_POSTGRES

defaults:
  mode: full-refresh       # ou "incremental" si tu as une clé primaire
  object: "qa_{stream_table}" 
  schema: raw

streams:
    dbo.DS2Company:
      object: qa_ds2company
      meta:
        dagster:
          asset_key: ["raw", "qa_ds2company"]   # hiérarchie de l’asset key
          group: "ref_data"