"""empty message

Revision ID: 944c7b5ba8db
Revises: 0002_create_ref_data_schema
Create Date: 2025-11-07 14:50:54.791529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '944c7b5ba8db'
down_revision: Union[str, Sequence[str], None] = '0002_create_ref_data_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('country_id', name=op.f('pk_country')),
    sa.UniqueConstraint('code', name=op.f('uq_country__code')),
    schema='ref_data'
    )
    op.create_table('currency',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('currency_id', name=op.f('pk_currency')),
    sa.UniqueConstraint('code', name=op.f('uq_currency__code')),
    schema='ref_data'
    )
    op.create_table('entity',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_entity')),
    schema='ref_data'
    )
    op.create_table('entity_type',
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('entity_type_id', name=op.f('pk_entity_type')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_entity_type__mnemonic')),
    schema='ref_data'
    )
    op.create_table('equity_type',
    sa.Column('equity_type_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('mnemonic', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('equity_type_id', name=op.f('pk_equity_type')),
    sa.UniqueConstraint('description', name=op.f('uq_equity_type__description')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_equity_type__mnemonic')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_equity_type__mnemonic')),
    schema='ref_data'
    )
    op.create_table('instrument_type',
    sa.Column('instrument_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sys_period', postgresql.TSTZRANGE(), server_default=sa.text('tstzrange(current_timestamp, NULL)'), nullable=False),
    sa.PrimaryKeyConstraint('instrument_type_id', name=op.f('pk_instrument_type')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_instrument_type__mnemonic')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_instrument_type__mnemonic')),
    sa.UniqueConstraint('name', name=op.f('uq_instrument_type__name')),
    schema='ref_data'
    )
    op.create_table('venue_type',
    sa.Column('venue_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('venue_type_id', name=op.f('pk_venue_type')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_venue_type__mnemonic')),
    schema='ref_data'
    )
    op.create_table('weblink_type',
    sa.Column('weblink_type_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('weblink_type_id', name=op.f('pk_weblink_type')),
    schema='ref_data'
    )
    op.create_table('classification_system',
    sa.Column('classification_system_id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['ref_data.entity_type.entity_type_id'], name=op.f('fk_classification_system__entity_type_id__entity_type')),
    sa.PrimaryKeyConstraint('classification_system_id', name=op.f('pk_classification_system')),
    schema='ref_data'
    )
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_count_date', sa.Date(), nullable=True),
    sa.Column('st_address_1', sa.String(length=100), nullable=True),
    sa.Column('st_address_2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('public_since', sa.Date(), nullable=True),
    sa.Column('common_shareholders', sa.BigInteger(), nullable=True),
    sa.Column('common_shareholders_date', sa.Date(), nullable=True),
    sa.Column('total_shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding_updated_at', sa.Date(), nullable=True),
    sa.Column('total_float_shares', sa.BigInteger(), nullable=True),
    sa.Column('estimates_currency_id', sa.Integer(), nullable=True),
    sa.Column('statements_currency_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_financial_at', sa.Date(), nullable=True),
    sa.Column('last_modified_non_financial_at', sa.Date(), nullable=True),
    sa.Column('latest_annual_financial_date', sa.Date(), nullable=True),
    sa.Column('latest_interim_financial_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['ref_data.entity.entity_id'], name=op.f('fk_company__company_id__entity')),
    sa.ForeignKeyConstraint(['country_id'], ['ref_data.country.country_id'], name=op.f('fk_company__country_id__country')),
    sa.ForeignKeyConstraint(['estimates_currency_id'], ['ref_data.currency.currency_id'], name=op.f('fk_company__estimates_currency_id__currency')),
    sa.ForeignKeyConstraint(['statements_currency_id'], ['ref_data.currency.currency_id'], name=op.f('fk_company__statements_currency_id__currency')),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_company')),
    schema='ref_data'
    )
    op.create_table('instrument',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['ref_data.entity.entity_id'], name=op.f('fk_instrument__entity_id__entity')),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['ref_data.instrument_type.instrument_type_id'], name=op.f('fk_instrument__instrument_type_id__instrument_type')),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument')),
    schema='ref_data'
    )
    op.create_table('venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mnemonic', sa.String(length=20), nullable=True),
    sa.Column('venue_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['ref_data.country.country_id'], name=op.f('fk_venue__country_id__country')),
    sa.ForeignKeyConstraint(['venue_type_id'], ['ref_data.venue_type.venue_type_id'], name=op.f('fk_venue__venue_type_id__venue_type')),
    sa.PrimaryKeyConstraint('venue_id', name=op.f('pk_venue')),
    schema='ref_data'
    )
    op.create_table('classification_level',
    sa.Column('classification_level_id', sa.Integer(), nullable=False),
    sa.Column('classification_system_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['classification_system_id'], ['ref_data.classification_system.classification_system_id'], name=op.f('fk_classification_level__classification_system_id__classification_system')),
    sa.PrimaryKeyConstraint('classification_level_id', name=op.f('pk_classification_level')),
    schema='ref_data'
    )
    op.create_table('company_mapping',
    sa.Column('internal_company_id', sa.Integer(), nullable=False),
    sa.Column('external_company_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['internal_company_id'], ['ref_data.company.company_id'], name=op.f('fk_company_mapping__internal_company_id__company')),
    sa.PrimaryKeyConstraint('internal_company_id', name=op.f('pk_company_mapping')),
    sa.UniqueConstraint('source', 'external_company_id', name=op.f('uq_company_mapping__source')),
    schema='ref_data'
    )
    op.create_index('idx_source_external_company_id', 'company_mapping', ['source', 'external_company_id'], unique=False, schema='ref_data')
    op.create_table('company_weblink',
    sa.Column('company_weblink_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('weblink_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['ref_data.company.company_id'], name=op.f('fk_company_weblink__company_id__company')),
    sa.ForeignKeyConstraint(['weblink_type_id'], ['ref_data.weblink_type.weblink_type_id'], name=op.f('fk_company_weblink__weblink_type_id__weblink_type')),
    sa.PrimaryKeyConstraint('company_weblink_id', name=op.f('pk_company_weblink')),
    sa.UniqueConstraint('company_id', 'weblink_type_id', name='uq_company_weblink_type_id'),
    schema='ref_data'
    )
    op.create_table('equity',
    sa.Column('equity_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('sedol', sa.String(length=7), nullable=True),
    sa.Column('ric', sa.String(length=20), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('delistd_date', sa.Date(), nullable=True),
    sa.Column('equity_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('issue_type', sa.String(length=1), nullable=True),
    sa.Column('issue_description', sa.String(length=100), nullable=True),
    sa.Column('div_unit', sa.String(length=5), nullable=True),
    sa.Column('is_major_security', sa.Boolean(), nullable=False),
    sa.Column('is_primary_country', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('split_date', sa.Date(), nullable=True),
    sa.Column('split_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['ref_data.country.country_id'], name=op.f('fk_equity__country_id__country')),
    sa.ForeignKeyConstraint(['equity_id'], ['ref_data.instrument.instrument_id'], name=op.f('fk_equity__equity_id__instrument')),
    sa.ForeignKeyConstraint(['equity_type_id'], ['ref_data.equity_type.equity_type_id'], name=op.f('fk_equity__equity_type_id__equity_type')),
    sa.PrimaryKeyConstraint('equity_id', name=op.f('pk_equity')),
    schema='ref_data'
    )
    op.create_table('instrument_mapping',
    sa.Column('internal_instrument_id', sa.Integer(), nullable=False),
    sa.Column('external_instrument_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['internal_instrument_id'], ['ref_data.instrument.instrument_id'], name=op.f('fk_instrument_mapping__internal_instrument_id__instrument')),
    sa.PrimaryKeyConstraint('internal_instrument_id', name=op.f('pk_instrument_mapping')),
    sa.UniqueConstraint('source', 'external_instrument_id', name=op.f('uq_instrument_mapping__source')),
    schema='ref_data'
    )
    op.create_index('idx_source_external_instrument_id', 'instrument_mapping', ['source', 'external_instrument_id'], unique=False, schema='ref_data')
    op.create_table('quote',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('delisted_date', sa.Date(), nullable=True),
    sa.Column('mic', sa.String(length=12), nullable=True),
    sa.Column('market_name', sa.String(length=50), nullable=True),
    sa.Column('price_unit', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['ref_data.currency.currency_id'], name=op.f('fk_quote__currency_id__currency')),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_data.instrument.instrument_id'], name=op.f('fk_quote__instrument_id__instrument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['ref_data.venue.venue_id'], name=op.f('fk_quote__venue_id__venue')),
    sa.PrimaryKeyConstraint('quote_id', name=op.f('pk_quote')),
    schema='ref_data'
    )
    op.create_table('venue_mapping',
    sa.Column('internal_venue_id', sa.Integer(), nullable=False),
    sa.Column('external_venue_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['internal_venue_id'], ['ref_data.venue.venue_id'], name=op.f('fk_venue_mapping__internal_venue_id__venue')),
    sa.PrimaryKeyConstraint('internal_venue_id', name=op.f('pk_venue_mapping')),
    sa.UniqueConstraint('source', 'external_venue_id', name=op.f('uq_venue_mapping__source')),
    schema='ref_data'
    )
    op.create_index('idx__source_external_venue_id', 'venue_mapping', ['source', 'external_venue_id'], unique=False, schema='ref_data')
    op.create_table('classification_node',
    sa.Column('classification_node_id', sa.Integer(), nullable=False),
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('classification_level_id', sa.Integer(), nullable=False),
    sa.Column('classification_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['classification_level_id'], ['ref_data.classification_level.classification_level_id'], name=op.f('fk_classification_node__classification_level_id__classification_level')),
    sa.ForeignKeyConstraint(['classification_system_id'], ['ref_data.classification_system.classification_system_id'], name=op.f('fk_classification_node__classification_system_id__classification_system')),
    sa.ForeignKeyConstraint(['parent_node_id'], ['ref_data.classification_node.classification_node_id'], name=op.f('fk_classification_node__parent_node_id__classification_node')),
    sa.PrimaryKeyConstraint('classification_node_id', name=op.f('pk_classification_node')),
    schema='ref_data'
    )
    op.create_table('quote_mapping',
    sa.Column('internal_quote_id', sa.Integer(), nullable=False),
    sa.Column('external_quote_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['internal_quote_id'], ['ref_data.quote.quote_id'], name=op.f('fk_quote_mapping__internal_quote_id__quote')),
    sa.PrimaryKeyConstraint('internal_quote_id', name=op.f('pk_quote_mapping')),
    sa.UniqueConstraint('source', 'external_quote_id', name=op.f('uq_quote_mapping__source')),
    schema='ref_data'
    )
    op.create_index('idx_source_external_quote_id', 'quote_mapping', ['source', 'external_quote_id'], unique=False, schema='ref_data')
    op.create_table('entity_classification',
    sa.Column('entity_classification_id', sa.Integer(), nullable=False),
    sa.Column('classification_node_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('classification_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['classification_node_id'], ['ref_data.classification_node.classification_node_id'], name=op.f('fk_entity_classification__classification_node_id__classification_node')),
    sa.ForeignKeyConstraint(['classification_system_id'], ['ref_data.classification_system.classification_system_id'], name=op.f('fk_entity_classification__classification_system_id__classification_system')),
    sa.ForeignKeyConstraint(['entity_id'], ['ref_data.entity.entity_id'], name=op.f('fk_entity_classification__entity_id__entity')),
    sa.PrimaryKeyConstraint('entity_classification_id', name=op.f('pk_entity_classification')),
    schema='ref_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_classification', schema='ref_data')
    op.drop_index('idx_source_external_quote_id', table_name='quote_mapping', schema='ref_data')
    op.drop_table('quote_mapping', schema='ref_data')
    op.drop_table('classification_node', schema='ref_data')
    op.drop_index('idx__source_external_venue_id', table_name='venue_mapping', schema='ref_data')
    op.drop_table('venue_mapping', schema='ref_data')
    op.drop_table('quote', schema='ref_data')
    op.drop_index('idx_source_external_instrument_id', table_name='instrument_mapping', schema='ref_data')
    op.drop_table('instrument_mapping', schema='ref_data')
    op.drop_table('equity', schema='ref_data')
    op.drop_table('company_weblink', schema='ref_data')
    op.drop_index('idx_source_external_company_id', table_name='company_mapping', schema='ref_data')
    op.drop_table('company_mapping', schema='ref_data')
    op.drop_table('classification_level', schema='ref_data')
    op.drop_table('venue', schema='ref_data')
    op.drop_table('instrument', schema='ref_data')
    op.drop_table('company', schema='ref_data')
    op.drop_table('classification_system', schema='ref_data')
    op.drop_table('weblink_type', schema='ref_data')
    op.drop_table('venue_type', schema='ref_data')
    op.drop_table('instrument_type', schema='ref_data')
    op.drop_table('equity_type', schema='ref_data')
    op.drop_table('entity_type', schema='ref_data')
    op.drop_table('entity', schema='ref_data')
    op.drop_table('currency', schema='ref_data')
    op.drop_table('country', schema='ref_data')
    # ### end Alembic commands ###
