"""empty message

Revision ID: e8e9285ce749
Revises: 
Create Date: 2025-11-04 10:02:50.608892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e9285ce749'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_mapping',
    sa.Column('internal_company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_company_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('internal_company_id', name=op.f('pk_company_mapping')),
    sa.UniqueConstraint('source', 'external_company_id', name=op.f('uq_company_mapping__source')),
    schema='ref_data'
    )
    op.create_index('idx_company_mapping_source_external', 'company_mapping', ['source', 'external_company_id'], unique=False, schema='ref_data')
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('country_id', name=op.f('pk_country')),
    sa.UniqueConstraint('code', name=op.f('uq_country__code')),
    schema='ref_data'
    )
    op.create_table('currency',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('currency_id', name=op.f('pk_currency')),
    sa.UniqueConstraint('code', name=op.f('uq_currency__code')),
    schema='ref_data'
    )
    op.create_table('entity',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_entity')),
    schema='ref_data'
    )
    op.create_table('entity_type',
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('entity_type_id', name=op.f('pk_entity_type')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_entity_type__mnemonic')),
    schema='ref_data'
    )
    op.create_table('instrument_mapping',
    sa.Column('internal_instrument_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_instrument_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('internal_instrument_id', name=op.f('pk_instrument_mapping')),
    sa.UniqueConstraint('source', 'external_instrument_id', name=op.f('uq_instrument_mapping__source')),
    schema='ref_data'
    )
    op.create_table('instrument_type',
    sa.Column('instrument_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('instrument_type_id', name=op.f('pk_instrument_type')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_instrument_type__mnemonic')),
    sa.UniqueConstraint('name', name=op.f('uq_instrument_type__name')),
    schema='ref_data'
    )
    op.create_table('venue_mapping',
    sa.Column('internal_venue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_venue_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('internal_venue_id', name=op.f('pk_venue_mapping')),
    sa.UniqueConstraint('source', 'external_venue_id', name=op.f('uq_venue_mapping__source')),
    schema='ref_data'
    )
    op.create_index('idx_external_mapping_source_external', 'venue_mapping', ['source', 'external_venue_id'], unique=False, schema='ref_data')
    op.create_table('venue_type',
    sa.Column('venue_type_id', sa.Integer(), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('venue_type_id', name=op.f('pk_venue_type')),
    sa.UniqueConstraint('mnemonic', name=op.f('uq_venue_type__mnemonic')),
    schema='ref_data'
    )
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['ref_data.entity.entity_id'], name=op.f('fk_company__company_id__entity')),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_company')),
    schema='ref_data'
    )
    op.create_table('instrument',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['ref_data.entity.entity_id'], name=op.f('fk_instrument__entity_id__entity')),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['ref_data.instrument_type.instrument_type_id'], name=op.f('fk_instrument__instrument_type_id__instrument_type')),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument')),
    schema='ref_data'
    )
    op.create_table('venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('venue_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_type_id'], ['ref_data.venue_type.venue_type_id'], name=op.f('fk_venue__venue_type_id__venue_type')),
    sa.PrimaryKeyConstraint('venue_id', name=op.f('pk_venue')),
    schema='ref_data'
    )
    op.create_table('equity',
    sa.Column('equity_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['equity_id'], ['ref_data.instrument.instrument_id'], name=op.f('fk_equity__equity_id__instrument')),
    sa.PrimaryKeyConstraint('equity_id', name=op.f('pk_equity')),
    schema='ref_data'
    )
    op.create_table('quote',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('delisted_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('mic', sa.String(), nullable=True),
    sa.Column('price_unit', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_data.instrument.instrument_id'], name=op.f('fk_quote__instrument_id__instrument')),
    sa.ForeignKeyConstraint(['venue_id'], ['ref_data.venue.venue_id'], name=op.f('fk_quote__venue_id__venue')),
    sa.PrimaryKeyConstraint('quote_id', name=op.f('pk_quote')),
    schema='ref_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote', schema='ref_data')
    op.drop_table('equity', schema='ref_data')
    op.drop_table('venue', schema='ref_data')
    op.drop_table('instrument', schema='ref_data')
    op.drop_table('company', schema='ref_data')
    op.drop_table('venue_type', schema='ref_data')
    op.drop_index('idx_external_mapping_source_external', table_name='venue_mapping', schema='ref_data')
    op.drop_table('venue_mapping', schema='ref_data')
    op.drop_table('instrument_type', schema='ref_data')
    op.drop_table('instrument_mapping', schema='ref_data')
    op.drop_table('entity_type', schema='ref_data')
    op.drop_table('entity', schema='ref_data')
    op.drop_table('currency', schema='ref_data')
    op.drop_table('country', schema='ref_data')
    op.drop_index('idx_company_mapping_source_external', table_name='company_mapping', schema='ref_data')
    op.drop_table('company_mapping', schema='ref_data')
    # ### end Alembic commands ###
