"""Unit tests for utils/columns.py - Column classification and FK detection."""

import pytest
from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey
from unittest.mock import MagicMock

from master_instrument.etl.loading.utils.columns import (
    has_default_value,
    is_auto_pk,
    is_auto_generated,
    get_auto_generated_column_names,
    is_mixin_with_table,
    extract_mixin_columns,
    get_mixin_columns_from_mro,
    get_known_mixin_columns,
    get_mixin_columns,
    get_mixin_exclusions,
    get_auto_exclusions,
    build_excluded_columns,
    get_all_columns,
    get_fk_column_name,
    matches_fk_pattern,
    detect_fk_column,
    detect_fk_by_column_pattern,
    KNOWN_MIXIN_COLUMNS,
)


class TestHasDefaultValue:
    """Tests for has_default_value().
    
    Note: has_default_value now only returns True for truly auto-generated
    defaults like now(), CURRENT_TIMESTAMP, tstzrange(), etc.
    Simple defaults like 'false', 'true', '0' are NOT considered auto-generated.
    """
    
    def test_detects_auto_generated_server_default(self):
        """Should detect truly auto-generated server_default like now()."""
        col = MagicMock()
        col.server_default = MagicMock()
        col.server_default.arg = "now()"
        col.default = None
        assert has_default_value(col) is True
    
    def test_detects_current_timestamp(self):
        """Should detect CURRENT_TIMESTAMP as auto-generated."""
        col = MagicMock()
        col.server_default = MagicMock()
        col.server_default.arg = "CURRENT_TIMESTAMP"
        col.default = None
        assert has_default_value(col) is True
    
    def test_does_not_exclude_boolean_false_default(self):
        """Should NOT exclude simple boolean defaults like 'false'."""
        col = MagicMock()
        col.server_default = MagicMock()
        col.server_default.arg = "false"
        col.default = None
        assert has_default_value(col) is False  # Simple default, not auto-generated
    
    def test_does_not_exclude_boolean_true_default(self):
        """Should NOT exclude simple boolean defaults like 'true'."""
        col = MagicMock()
        col.server_default = MagicMock()
        col.server_default.arg = "true"
        col.default = None
        assert has_default_value(col) is False  # Simple default, not auto-generated
    
    def test_python_default_not_excluded(self):
        """Python-side defaults should NOT cause exclusion."""
        col = MagicMock()
        col.server_default = None
        col.default = "value"
        assert has_default_value(col) is False  # Python default, not DB auto-generated
    
    def test_returns_false_when_no_default(self):
        """Should return False when no default."""
        col = MagicMock()
        col.server_default = None
        col.default = None
        assert has_default_value(col) is False


class TestIsAutoPk:
    """Tests for is_auto_pk() - detects auto-increment primary keys.
    
    Convention: Only explicit autoincrement=True is considered auto-increment.
    This is an explicit convention - models must set autoincrement=True on SERIAL PKs.
    """
    
    def test_detects_explicit_autoincrement_pk(self):
        """Should detect PK with autoincrement=True."""
        col = MagicMock()
        col.primary_key = True
        col.autoincrement = True
        assert is_auto_pk(col) is True
    
    def test_rejects_autoincrement_auto(self):
        """Should NOT detect PK with autoincrement='auto' (default)."""
        col = MagicMock()
        col.primary_key = True
        col.autoincrement = 'auto'
        assert is_auto_pk(col) is False
    
    def test_rejects_non_pk(self):
        """Should reject non-primary key columns."""
        col = MagicMock()
        col.primary_key = False
        col.autoincrement = True
        assert is_auto_pk(col) is False
    
    def test_rejects_autoincrement_false(self):
        """Should reject when autoincrement=False."""
        col = MagicMock()
        col.primary_key = True
        col.autoincrement = False
        assert is_auto_pk(col) is False
    
    def test_rejects_composite_pk_without_explicit_autoincrement(self):
        """Composite PK members without explicit autoincrement=True should be rejected."""
        col = MagicMock()
        col.primary_key = True
        col.autoincrement = 'auto'  # Default, not explicit
        assert is_auto_pk(col) is False


class TestIsAutoGenerated:
    """Tests for is_auto_generated()."""
    
    def test_detects_server_default_now(self):
        """Should detect column with server_default=now()."""
        col = MagicMock()
        col.server_default = MagicMock()
        col.server_default.arg = "now()"
        col.default = None
        col.primary_key = False
        col.autoincrement = False
        assert is_auto_generated(col) is True
    
    def test_detects_explicit_autoincrement_pk(self):
        """Should detect column with autoincrement=True."""
        col = MagicMock()
        col.server_default = None
        col.default = None
        col.primary_key = True
        col.autoincrement = True
        assert is_auto_generated(col) is True
    
    def test_rejects_implicit_autoincrement_pk(self):
        """Should NOT detect PK with autoincrement='auto' (not explicit)."""
        col = MagicMock()
        col.server_default = None
        col.default = None
        col.primary_key = True
        col.autoincrement = 'auto'
        # With explicit convention, autoincrement='auto' is NOT considered auto-generated
        assert is_auto_generated(col) is False
    
    def test_rejects_regular_column(self):
        """Should reject regular column."""
        col = MagicMock()
        col.server_default = None
        col.default = None
        col.primary_key = False
        col.autoincrement = False
        assert is_auto_generated(col) is False
    
    def test_rejects_boolean_server_default(self):
        """Should NOT exclude columns with simple boolean defaults."""
        col = MagicMock()
        col.server_default = MagicMock()
        col.server_default.arg = "false"
        col.default = None
        col.primary_key = False
        col.autoincrement = False
        assert is_auto_generated(col) is False


class TestGetAutoGeneratedColumnNames:
    """Tests for get_auto_generated_column_names()."""
    
    def test_extracts_auto_generated_columns(self):
        """Should extract auto-generated column names."""
        metadata = MetaData()
        table = Table(
            "test", metadata,
            Column("id", Integer, primary_key=True, autoincrement=True),
            Column("name", String),
            Column("created_at", String, server_default="now()")
        )
        result = get_auto_generated_column_names(table)
        assert "id" in result
        assert "created_at" in result
        assert "name" not in result


class TestIsMixinWithTable:
    """Tests for is_mixin_with_table()."""
    
    def test_detects_mixin_with_table(self):
        """Should detect mixin with __table__."""
        mixin = MagicMock()
        mixin.__name__ = "AuditMixin"
        mixin.__table__ = MagicMock()
        assert is_mixin_with_table(mixin) is True
    
    def test_rejects_mixin_without_table(self):
        """Should reject mixin without __table__."""
        mixin = MagicMock()
        mixin.__name__ = "SomeMixin"
        delattr(mixin, '__table__')
        assert is_mixin_with_table(mixin) is False
    
    def test_rejects_non_mixin(self):
        """Should reject non-mixin class."""
        cls = MagicMock()
        cls.__name__ = "RegularClass"
        cls.__table__ = MagicMock()
        assert is_mixin_with_table(cls) is False


class TestExtractMixinColumns:
    """Tests for extract_mixin_columns()."""
    


class TestGetKnownMixinColumns:
    """Tests for get_known_mixin_columns()."""
    
    def test_extracts_known_mixin_columns(self):
        """Should extract known mixin columns present in model."""
        metadata = MetaData()
        table = Table(
            "test", metadata,
            Column("id", Integer),
            Column("created_at", String),
            Column("updated_at", String)
        )
        model = MagicMock()
        model.__table__ = table
        
        result = get_known_mixin_columns(model)
        assert "created_at" in result
        assert "updated_at" in result
    
    def test_returns_empty_when_no_mixin_columns(self):
        """Should return empty set when no mixin columns."""
        metadata = MetaData()
        table = Table("test", metadata, Column("id", Integer))
        model = MagicMock()
        model.__table__ = table
        
        result = get_known_mixin_columns(model)
        assert result == set()


class TestGetMixinExclusions:
    """Tests for get_mixin_exclusions()."""
    
    def test_returns_mixin_columns_when_enabled(self):
        """Should return mixin columns when exclude_mixins=True."""
        metadata = MetaData()
        table = Table(
            "test", metadata,
            Column("created_at", String),
            Column("updated_at", String)
        )
        model = MagicMock()
        model.__table__ = table
        model.__mro__ = [model, object]
        model.__name__ = "TestModel"
        
        result = get_mixin_exclusions(model, exclude_mixins=True)
        assert "created_at" in result
        assert "updated_at" in result
    
    def test_returns_empty_when_disabled(self):
        """Should return empty when exclude_mixins=False."""
        model = MagicMock()
        result = get_mixin_exclusions(model, exclude_mixins=False)
        assert result == set()


class TestGetAutoExclusions:
    """Tests for get_auto_exclusions()."""
    
    def test_returns_auto_columns_when_enabled(self):
        """Should return auto-generated columns when enabled."""
        metadata = MetaData()
        table = Table(
            "test", metadata,
            Column("id", Integer, primary_key=True, autoincrement=True),
            Column("name", String)
        )
        
        result = get_auto_exclusions(table, auto_exclude=True)
        assert "id" in result
        assert "name" not in result
    
    def test_returns_empty_when_disabled(self):
        """Should return empty when disabled."""
        metadata = MetaData()
        table = Table("test", metadata, Column("id", Integer, primary_key=True, autoincrement=True))
        
        result = get_auto_exclusions(table, auto_exclude=False)
        assert result == set()


class TestBuildExcludedColumns:
    """Tests for build_excluded_columns()."""
    
    def test_combines_all_exclusions(self):
        """Should combine explicit, mixin, and auto exclusions."""
        metadata = MetaData()
        table = Table(
            "test", metadata,
            Column("id", Integer, primary_key=True, autoincrement=True),
            Column("created_at", String),
            Column("name", String),
            Column("custom", String)
        )
        model = MagicMock()
        model.__table__ = table
        model.__mro__ = [model, object]
        model.__name__ = "TestModel"
        
        result = build_excluded_columns(
            table=table,
            exclude_columns=["custom"],
            exclude_mixins=True,
            auto_exclude_server_defaults=True,
            model=model
        )
        
        assert "created_at" in result  # Mixin
        assert "custom" in result  # Explicit


class TestGetAllColumns:
    """Tests for get_all_columns()."""
    
    def test_returns_all_non_excluded_columns(self):
        """Should return all columns except exclusions."""
        metadata = MetaData()
        table = Table(
            "test", metadata,
            Column("id", Integer, primary_key=True, autoincrement=True),
            Column("created_at", String),
            Column("name", String),
            Column("value", String)
        )
        model = MagicMock()
        model.__table__ = table
        model.__mro__ = [model, object]
        model.__name__ = "TestModel"
        
        result = get_all_columns(
            table,
            exclude_columns=["id"],
            exclude_mixins=False,
            auto_exclude_server_defaults=False,
            model=model
        )
        
        assert "name" in result
        assert "value" in result
        assert "id" not in result
        
        result = get_all_columns(
            table,
            exclude_columns=None,
            exclude_mixins=True,
            auto_exclude_server_defaults=True,
            model=model
        )
        
        assert "name" in result
        assert "value" in result
        assert "id" not in result
        assert "created_at" not in result  # Excluded as mixin column


class TestGetFkColumnName:
    """Tests for get_fk_column_name()."""
    
    def test_extracts_fk_column_name(self):
        """Should extract FK column name."""
        fk = MagicMock()
        col = MagicMock()
        col.name = "company_id"
        fk.columns = [col]
        
        result = get_fk_column_name(fk)
        assert result == "company_id"


class TestMatchesFkPattern:
    """Tests for matches_fk_pattern()."""
    
    def test_matches_pattern_in_referred_table(self):
        """Should match pattern in referred table name."""
        fk = MagicMock()
        fk.referred_table.fullname = "master.data_source"
        
        assert matches_fk_pattern(fk, "data_source") is True
    
    def test_rejects_non_matching_pattern(self):
        """Should reject non-matching pattern."""
        fk = MagicMock()
        fk.referred_table.fullname = "master.company"
        
        assert matches_fk_pattern(fk, "data_source") is False
    
    def test_handles_exception_gracefully(self):
        """Should return False on exception."""
        fk = MagicMock()
        fk.referred_table.side_effect = Exception()
        
        assert matches_fk_pattern(fk, "pattern") is False


class TestDetectFkColumn:
    """Tests for detect_fk_column()."""
    
    def test_detects_fk_by_pattern(self):
        """Should detect FK by referred table pattern."""
        metadata = MetaData()
        ref_table = Table("data_source", metadata, Column("id", Integer, primary_key=True))
        table = Table(
            "test", metadata,
            Column("id", Integer, primary_key=True),
            Column("data_source_id", Integer, ForeignKey("data_source.id"))
        )
        
        result = detect_fk_column(table, "data_source")
        assert result == "data_source_id"
    
    def test_uses_fallback_when_pattern_fails(self):
        """Should use fallback when pattern doesn't match."""
        metadata = MetaData()
        ref_table = Table("other", metadata, Column("id", Integer, primary_key=True))
        table = Table(
            "test", metadata,
            Column("id", Integer, primary_key=True),
            Column("source_id", Integer, ForeignKey("other.id"))
        )
        
        result = detect_fk_column(table, "data_source", fallback="source_id")
        assert result == "source_id"
    
    def test_returns_none_when_no_match(self):
        """Should return None when no match."""
        metadata = MetaData()
        table = Table("test", metadata, Column("id", Integer, primary_key=True))
        
        result = detect_fk_column(table, "data_source")
        assert result is None


class TestDetectFkByColumnPattern:
    """Tests for detect_fk_by_column_pattern()."""
    
    def test_detects_fk_by_column_prefix(self):
        """Should detect FK by column name prefix."""
        metadata = MetaData()
        ref_table = Table("entity", metadata, Column("id", Integer, primary_key=True))
        table = Table(
            "test", metadata,
            Column("id", Integer, primary_key=True),
            Column("internal_company_id", Integer, ForeignKey("entity.id"))
        )
        
        result = detect_fk_by_column_pattern(table, "internal_")
        assert result == "internal_company_id"
    
    def test_returns_none_when_no_match(self):
        """Should return None when no matching FK."""
        metadata = MetaData()
        table = Table("test", metadata, Column("id", Integer, primary_key=True))
        
        result = detect_fk_by_column_pattern(table, "internal_")
        assert result is None
