sources:
  - name: raw
    tables:
      - name: qa_DS2PrimQtPrc
        meta:
          dagster:
            asset_key: qa_ds2primqtprc
      - name: qa_DS2MktVal
        meta:
          dagster:
            asset_key: qa_ds2mktval
      - name: qa_DS2Adj
        meta:
          dagster:
            asset_key: qa_ds2adj
      - name: qa_DS2Security
        meta:
          dagster:
            asset_key: qa_ds2security
      - name: qa_DS2Company
        meta:
          dagster:
            asset_key: qa_ds2company
      - name: qa_DS2CtryQtInfo
        meta:
          dagster:
            asset_key: qa_ds2ctryqtinfo
      - name: qa_RKDFndCmpRefIssue
        meta:
          dagster:
            asset_key: qa_rkdfndcmprefissue
      - name: qa_RKDFndCmpFiling
        meta:
          dagster:
            asset_key: qa_rkdfndcmpfiling
      - name: qa_RKDFndCmpDet
        meta:
          dagster:
            asset_key: qa_rkdfndcmpdet
      - name: qa_RKDFndCmpRef
        meta:
          dagster:
            asset_key: qa_rkdfndcmpref
      - name: qa_RKDFndCmpWebLink
        meta:
          dagster:
            asset_key: qa_rkdfndcmpweblink
      - name: qa_DS2FxRate
        meta:
          dagster:
            asset_key: qa_ds2fxrate
      - name: qa_DS2Exchange
        meta:
          dagster:
            asset_key: qa_ds2exchange
      - name: qa_DS2ExchQtInfo
        meta:
          dagster:
            asset_key: qa_ds2exchqtinfo
      - name: qa_DS2XRef
        meta:
          dagster:
            asset_key: qa_ds2xref
      - name: wb_news
        meta:
          dagster:
            asset_key: wb_news
