"""empty message

Revision ID: 0004_create_tables
Revises: 0003_timescaledb_extension
Create Date: 2025-11-12 18:23:29.766779

"""
# pyright: reportUnknownArgumentType=false
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004_create_tables'
down_revision: Union[str, Sequence[str], None] = '0003_timescaledb_extension'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_scheme',
    sa.Column('classification_scheme_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('classification_scheme_id', name=op.f('pk_classification_scheme')),
    sa.UniqueConstraint('mnemonic', name='uq_classification_scheme_mnemonic'),
    sa.UniqueConstraint('name', name='uq_classification_scheme_name'),
    schema='master'
    )
    op.create_table('company_market_cap_load',
    sa.Column('company_market_cap_load_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_source_version', sa.BigInteger(), nullable=False),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('company_market_cap_load_id', name=op.f('pk_company_market_cap_load')),
    schema='master'
    )
    op.create_index('idx_company_market_cap_load_time', 'company_market_cap_load', ['loaded_at'], unique=False, schema='master')
    op.create_table('corpact_type',
    sa.Column('corpact_type_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('corpact_type_id', name=op.f('pk_corpact_type')),
    sa.UniqueConstraint('code', name='uq_corpact_type_code'),
    schema='master'
    )
    op.create_table('country',
    sa.Column('country_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code_alpha2', sa.CHAR(length=2), nullable=False),
    sa.Column('code_alpha3', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('country_id', name=op.f('pk_country')),
    sa.UniqueConstraint('code_alpha2', name='uq_country_code_alpha2'),
    sa.UniqueConstraint('code_alpha3', name='uq_country_code_alpha3'),
    schema='master'
    )
    op.create_table('currency',
    sa.Column('currency_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('currency_id', name=op.f('pk_currency')),
    sa.UniqueConstraint('code', name='uq_currency_code'),
    schema='master'
    )
    op.create_table('data_source',
    sa.Column('data_source_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('mnemonic', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('data_source_id', name=op.f('pk_data_source')),
    sa.UniqueConstraint('mnemonic', name='uq_data_source_mnemonic'),
    schema='master'
    )
    op.create_table('dividend_type',
    sa.Column('dividend_type_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dividend_type_id', name=op.f('pk_dividend_type')),
    sa.UniqueConstraint('code', name='uq_dividend_type_code'),
    schema='master'
    )
    op.create_table('entity_type',
    sa.Column('entity_type_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('entity_type_id', name=op.f('pk_entity_type')),
    sa.UniqueConstraint('mnemonic', name='uq_entity_type_mnemonic'),
    schema='master'
    )
    op.create_table('equity_type',
    sa.Column('equity_type_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('equity_type_id', name=op.f('pk_equity_type')),
    sa.UniqueConstraint('description', name='uq_equity_type_description'),
    sa.UniqueConstraint('mnemonic', name='uq_equity_type_mnemonic'),
    schema='master'
    )
    op.create_table('financial_period_type',
    sa.Column('financial_period_type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=True),
    sa.Column('months', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('financial_period_type_id', name=op.f('pk_financial_period_type')),
    sa.UniqueConstraint('mnemonic', name='uq_financial_period_type_mnemonic'),
    sa.UniqueConstraint('months', name='uq_financial_period_type_months'),
    sa.UniqueConstraint('name', name='uq_financial_period_type_name'),
    schema='master'
    )
    op.create_table('financial_statement_type',
    sa.Column('financial_statement_type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('financial_statement_type_id', name=op.f('pk_financial_statement_type')),
    sa.UniqueConstraint('mnemonic', name='uq_financial_statement_type_mnemonic'),
    sa.UniqueConstraint('name', name='uq_financial_statement_type_name'),
    schema='master'
    )
    op.create_table('instrument_type',
    sa.Column('instrument_type_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('instrument_type_id', name=op.f('pk_instrument_type')),
    sa.UniqueConstraint('mnemonic', name='uq_instrument_type_mnemonic'),
    schema='master'
    )
    op.create_table('market_data_load',
    sa.Column('market_data_load_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_source_version', sa.BigInteger(), nullable=False),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('market_data_load_id', name=op.f('pk_market_data_load')),
    schema='master'
    )
    op.create_index('idx_market_data_load_time', 'market_data_load', ['loaded_at'], unique=False, schema='master')
    op.create_table('total_return_load',
    sa.Column('total_return_load_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_source_version', sa.BigInteger(), nullable=False),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('total_return_load_id', name=op.f('pk_total_return_load')),
    schema='master'
    )
    op.create_index('idx_total_return_load_time', 'total_return_load', ['loaded_at'], unique=False, schema='master')
    op.create_table('region',
    sa.Column('region_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk_region')),
    sa.UniqueConstraint('code', name='uq_region_code'),
    schema='master'
    )
    op.create_table('std_financial_value_load',
    sa.Column('std_financial_value_load_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_source_version', sa.BigInteger(), nullable=False),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('std_financial_value_load_id', name=op.f('pk_std_financial_value_load')),
    schema='master'
    )
    op.create_index('idx_std_financial_value_load_time', 'std_financial_value_load', ['loaded_at'], unique=False, schema='master')
    op.create_table('venue_type',
    sa.Column('venue_type_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('venue_type_id', name=op.f('pk_venue_type')),
    sa.UniqueConstraint('mnemonic', name='uq_venue_type_mnemonic'),
    schema='master'
    )
    op.create_table('weblink_type',
    sa.Column('weblink_type_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('weblink_type_id', name=op.f('pk_weblink_type')),
    sa.UniqueConstraint('description', name='uq_weblink_type_description'),
    schema='master'
    )
    op.create_table('classification_level',
    sa.Column('classification_scheme_id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['classification_scheme_id'], ['master.classification_scheme.classification_scheme_id'], name=op.f('fk_classification_level__classification_scheme_id__classification_scheme'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('classification_scheme_id', 'level_number', name='pk_classification_level'),
    sa.UniqueConstraint('classification_scheme_id', 'name', name='uq_classification_level_scheme_name'),
    schema='master'
    )
    op.create_table('country_region',
    sa.Column('country_id', sa.SmallInteger(), nullable=False),
    sa.Column('region_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['master.country.country_id'], name=op.f('fk_country_region__country_id__country'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['master.region.region_id'], name=op.f('fk_country_region__region_id__region'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('country_id', 'region_id', name='pk_country_region'),
    schema='master'
    )
    op.create_table('currency_pair',
    sa.Column('currency_pair_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('quote_currency_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['master.currency.currency_id'], name=op.f('fk_currency_pair__base_currency_id__currency'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_currency_id'], ['master.currency.currency_id'], name=op.f('fk_currency_pair__quote_currency_id__currency'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('currency_pair_id', name=op.f('pk_currency_pair')),
    sa.UniqueConstraint('base_currency_id', 'quote_currency_id', name='uq_currency_pair_base_quote'),
    schema='master'
    )
    op.create_index('idx_currency_pair_base', 'currency_pair', ['base_currency_id'], unique=False, schema='master')
    op.create_index('idx_currency_pair_quote', 'currency_pair', ['quote_currency_id'], unique=False, schema='master')
    op.create_table('entity',
    sa.Column('entity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_id'], ['master.entity_type.entity_type_id'], name=op.f('fk_entity__entity_type_id__entity_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_entity')),
    schema='master'
    )
    op.create_index('idx_entity_name', 'entity', ['name'], unique=False, schema='master')
    op.create_index('idx_entity_type_id', 'entity', ['entity_type_id'], unique=False, schema='master')
    op.create_table('fx_rate',
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('base_currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('quote_currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('mid_rate', sa.Double(), nullable=True),
    sa.Column('bid_rate', sa.Double(), nullable=True),
    sa.Column('ask_rate', sa.Double(), nullable=True),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['master.currency.currency_id'], name=op.f('fk_fx_rate__base_currency_id__currency'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_currency_id'], ['master.currency.currency_id'], name=op.f('fk_fx_rate__quote_currency_id__currency'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rate_date', 'base_currency_id', 'quote_currency_id', name='pk_fx_rate'),
    schema='master'
    )
    op.create_index('idx_fx_rate_base_currency_id_quote_currency_id', 'fx_rate', ['base_currency_id', 'quote_currency_id'], unique=False, schema='master')
    op.create_index('idx_fx_rate_base_currency_id_rate_date', 'fx_rate', ['base_currency_id', 'rate_date'], unique=False, schema='master')
    op.create_index('idx_fx_rate_currencies_rate_date', 'fx_rate', ['base_currency_id', 'quote_currency_id', sa.literal_column('rate_date DESC')], unique=False, schema='master')
    op.create_index('idx_fx_rate_loaded_at', 'fx_rate', ['loaded_at'], unique=False, schema='master')
    op.create_index('idx_fx_rate_rate_date', 'fx_rate', ['rate_date'], unique=False, schema='master')
    op.create_table('std_financial_item',
    sa.Column('std_financial_item_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('statement_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_currency', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['statement_type_id'], ['master.financial_statement_type.financial_statement_type_id'], name=op.f('fk_std_financial_item__statement_type_id__financial_statement_type'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('std_financial_item_id', name=op.f('pk_std_financial_item')),
    schema='master'
    )
    op.create_index('idx_std_financial_item_name', 'std_financial_item', ['name'], unique=False, schema='master')
    op.create_table('venue',
    sa.Column('venue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mnemonic', sa.String(length=10), nullable=False),
    sa.Column('venue_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('country_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['master.country.country_id'], name=op.f('fk_venue__country_id__country')),
    sa.ForeignKeyConstraint(['venue_type_id'], ['master.venue_type.venue_type_id'], name=op.f('fk_venue__venue_type_id__venue_type')),
    sa.PrimaryKeyConstraint('venue_id', name=op.f('pk_venue')),
    sa.UniqueConstraint('mnemonic', name='uq_venue_mnemonic'),
    schema='master'
    )
    op.create_table('classification_node',
    sa.Column('classification_scheme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('level_number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['classification_scheme_id', 'level_number'], ['master.classification_level.classification_scheme_id', 'master.classification_level.level_number'], name='fk_classification_node_level'),
    sa.ForeignKeyConstraint(['classification_scheme_id', 'parent_code'], ['master.classification_node.classification_scheme_id', 'master.classification_node.code'], name='fk_classification_node_parent', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classification_scheme_id'], ['master.classification_scheme.classification_scheme_id'], name=op.f('fk_classification_node__classification_scheme_id__classification_scheme'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('classification_scheme_id', 'code', name='pk_classification_node'),
    sa.UniqueConstraint('classification_scheme_id', 'name', 'level_number', name='uq_classification_node_scheme_id_name_level_number'),
    schema='master'
    )
    op.create_index('idx_classification_node_scheme_id_level_number', 'classification_node', ['classification_scheme_id', 'level_number'], unique=False, schema='master')
    op.create_index('idx_classification_node_scheme_id_parent_code', 'classification_node', ['classification_scheme_id', 'parent_code'], unique=False, schema='master')
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_count_date', sa.Date(), nullable=True),
    sa.Column('st_address_1', sa.String(length=100), nullable=True),
    sa.Column('st_address_2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.SmallInteger(), nullable=True),
    sa.Column('industry_code', sa.CHAR(length=3), nullable=True),
    sa.Column('public_since', sa.Date(), nullable=True),
    sa.Column('common_shareholders', sa.BigInteger(), nullable=True),
    sa.Column('common_shareholders_date', sa.Date(), nullable=True),
    sa.Column('total_shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding_updated_at', sa.Date(), nullable=True),
    sa.Column('total_float_shares', sa.BigInteger(), nullable=True),
    sa.Column('estimates_currency_id', sa.SmallInteger(), nullable=True),
    sa.Column('statements_currency_id', sa.SmallInteger(), nullable=True),
    sa.Column('ultimate_organization_id', sa.Integer(), nullable=True),
    sa.Column('primary_company_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_financial_at', sa.Date(), nullable=True),
    sa.Column('last_modified_non_financial_at', sa.Date(), nullable=True),
    sa.Column('latest_annual_financial_date', sa.Date(), nullable=True),
    sa.Column('latest_interim_financial_date', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['master.entity.entity_id'], name=op.f('fk_company__company_id__entity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['master.country.country_id'], name=op.f('fk_company__country_id__country')),
    sa.ForeignKeyConstraint(['estimates_currency_id'], ['master.currency.currency_id'], name=op.f('fk_company__estimates_currency_id__currency')),
    sa.ForeignKeyConstraint(['primary_company_id'], ['master.company.company_id'], name=op.f('fk_company__primary_company_id__company'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statements_currency_id'], ['master.currency.currency_id'], name=op.f('fk_company__statements_currency_id__currency')),
    sa.ForeignKeyConstraint(['ultimate_organization_id'], ['master.company.company_id'], name=op.f('fk_company__ultimate_organization_id__company'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_company')),
    schema='master'
    )
    op.create_table('entity_mapping',
    sa.Column('internal_entity_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.SmallInteger(), nullable=False),
    sa.Column('entity_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('external_entity_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['master.data_source.data_source_id'], name=op.f('fk_entity_mapping__data_source_id__data_source'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entity_type_id'], ['master.entity_type.entity_type_id'], name=op.f('fk_entity_mapping__entity_type_id__entity_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_entity_id'], ['master.entity.entity_id'], name=op.f('fk_entity_mapping__internal_entity_id__entity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('internal_entity_id', name=op.f('pk_entity_mapping')),
    sa.UniqueConstraint('data_source_id', 'entity_type_id', 'external_entity_id', name='uq_entity_mapping_ds_id_type_id_ext_id'),
    schema='master'
    )
    op.create_index('idx_entity_mapping_ext_id_ds_id_type_id', 'entity_mapping', ['external_entity_id', 'data_source_id', 'entity_type_id'], unique=False, schema='master')
    op.create_table('instrument',
    sa.Column('instrument_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['master.entity.entity_id'], name=op.f('fk_instrument__entity_id__entity'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['master.instrument_type.instrument_type_id'], name=op.f('fk_instrument__instrument_type_id__instrument_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument')),
    schema='master'
    )
    op.create_index('idx_instrument_entity_id', 'instrument', ['entity_id'], unique=False, schema='master')
    op.create_index('idx_instrument_symbol', 'instrument', ['symbol'], unique=False, schema='master')
    op.create_index('idx_instrument_type_id', 'instrument', ['instrument_type_id'], unique=False, schema='master')
    op.create_table('std_financial_item_mapping',
    sa.Column('internal_item_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.SmallInteger(), nullable=False),
    sa.Column('external_item_id', sa.String(length=100), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['master.data_source.data_source_id'], name=op.f('fk_std_financial_item_mapping__data_source_id__data_source'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_item_id'], ['master.std_financial_item.std_financial_item_id'], name=op.f('fk_std_financial_item_mapping__internal_item_id__std_financial_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('internal_item_id', name=op.f('pk_std_financial_item_mapping')),
    sa.UniqueConstraint('data_source_id', 'external_item_id', name='uq_std_financial_item_mapping_data_source_id_external_item_id'),
    schema='master'
    )
    op.create_index('idx_std_financial_item_mapping_external_item_id_data_source_id', 'std_financial_item_mapping', ['external_item_id', 'data_source_id'], unique=False, schema='master')
    op.create_table('venue_mapping',
    sa.Column('internal_venue_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.SmallInteger(), nullable=False),
    sa.Column('venue_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('external_venue_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['master.data_source.data_source_id'], name=op.f('fk_venue_mapping__data_source_id__data_source'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_venue_id'], ['master.venue.venue_id'], name=op.f('fk_venue_mapping__internal_venue_id__venue'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_type_id'], ['master.venue_type.venue_type_id'], name=op.f('fk_venue_mapping__venue_type_id__venue_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('internal_venue_id', name=op.f('pk_venue_mapping')),
    sa.UniqueConstraint('data_source_id', 'venue_type_id', 'external_venue_id', name='uq_venue_mapping_ds_id_type_id_ext_id'),
    schema='master'
    )
    op.create_index('idx_venue_mapping_ext_id_ds_id_type_id', 'venue_mapping', ['external_venue_id', 'data_source_id', 'venue_type_id'], unique=False, schema='master')
    op.create_table('company_market_cap',
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('market_cap', sa.Double(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['master.company.company_id'], name=op.f('fk_company_market_cap__company_id__company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['master.currency.currency_id'], name=op.f('fk_company_market_cap__currency_id__currency'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('valuation_date', 'company_id', name=op.f('pk_company_market_cap')),
    schema='master'
    )
    op.create_index('idx_company_market_cap_company_date', 'company_market_cap', ['company_id', 'valuation_date'], unique=False, schema='master')
    op.create_index('idx_company_market_cap_date', 'company_market_cap', ['valuation_date'], unique=False, schema='master')
    op.create_index('idx_company_market_cap_loaded_at', 'company_market_cap', ['loaded_at'], unique=False, schema='master')
    op.create_table('company_weblink',
    sa.Column('company_weblink_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('weblink_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['master.company.company_id'], name=op.f('fk_company_weblink__company_id__company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weblink_type_id'], ['master.weblink_type.weblink_type_id'], name=op.f('fk_company_weblink__weblink_type_id__weblink_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('company_weblink_id', name=op.f('pk_company_weblink')),
    sa.UniqueConstraint('company_id', 'weblink_type_id', name='uq_company_weblink_company_type'),
    schema='master'
    )
    op.create_table('entity_classification',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('classification_scheme_id', sa.Integer(), nullable=False),
    sa.Column('classification_node_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['classification_scheme_id', 'classification_node_code'], ['master.classification_node.classification_scheme_id', 'master.classification_node.code'], name='fk_entity_classification_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classification_scheme_id'], ['master.classification_scheme.classification_scheme_id'], name=op.f('fk_entity_classification__classification_scheme_id__classification_scheme'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['master.entity.entity_id'], name=op.f('fk_entity_classification__entity_id__entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'classification_scheme_id', name='pk_entity_classification'),
    schema='master'
    )
    op.create_table('equity',
    sa.Column('equity_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('sedol', sa.String(length=7), nullable=True),
    sa.Column('ric', sa.String(length=20), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('delisted_date', sa.Date(), nullable=True),
    sa.Column('equity_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('issue_type', sa.String(length=1), nullable=True),
    sa.Column('issue_description', sa.String(length=100), nullable=True),
    sa.Column('div_unit', sa.String(length=5), nullable=True),
    sa.Column('is_major_security', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('country_id', sa.SmallInteger(), nullable=True),
    sa.Column('split_date', sa.Date(), nullable=True),
    sa.Column('split_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['master.country.country_id'], name=op.f('fk_equity__country_id__country')),
    sa.ForeignKeyConstraint(['equity_id'], ['master.instrument.instrument_id'], name=op.f('fk_equity__equity_id__instrument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equity_type_id'], ['master.equity_type.equity_type_id'], name=op.f('fk_equity__equity_type_id__equity_type')),
    sa.PrimaryKeyConstraint('equity_id', name=op.f('pk_equity')),
    schema='master'
    )
    op.create_index('idx_equity_cusip', 'equity', ['cusip'], unique=False, schema='master')
    op.create_index('idx_equity_isin', 'equity', ['isin'], unique=False, schema='master')
    op.create_index('idx_equity_ric', 'equity', ['ric'], unique=False, schema='master')
    op.create_index('idx_equity_sedol', 'equity', ['sedol'], unique=False, schema='master')
    op.create_index('idx_equity_ticker', 'equity', ['ticker'], unique=False, schema='master')
    op.create_index('idx_equity_type_id', 'equity', ['equity_type_id'], unique=False, schema='master')
    op.create_table('instrument_mapping',
    sa.Column('internal_instrument_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.SmallInteger(), nullable=False),
    sa.Column('instrument_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('external_instrument_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['master.data_source.data_source_id'], name=op.f('fk_instrument_mapping__data_source_id__data_source'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['master.instrument_type.instrument_type_id'], name=op.f('fk_instrument_mapping__instrument_type_id__instrument_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_instrument_id'], ['master.instrument.instrument_id'], name=op.f('fk_instrument_mapping__internal_instrument_id__instrument'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('internal_instrument_id', name=op.f('pk_instrument_mapping')),
    sa.UniqueConstraint('data_source_id', 'instrument_type_id', 'external_instrument_id', name='uq_instrument_mapping_ds_id_type_id_ext_id'),
    schema='master'
    )
    op.create_index('idx_instrument_mapping_ext_id_ds_id_type_id', 'instrument_mapping', ['external_instrument_id', 'data_source_id', 'instrument_type_id'], unique=False, schema='master')
    op.create_table('quote',
    sa.Column('quote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=True),
    sa.Column('ric', sa.String(length=20), nullable=True),
    sa.Column('mic', sa.String(length=12), nullable=True),
    sa.Column('market_name', sa.String(length=50), nullable=True),
    sa.Column('price_unit', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['master.currency.currency_id'], name=op.f('fk_quote__currency_id__currency'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['master.instrument.instrument_id'], name=op.f('fk_quote__instrument_id__instrument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['master.venue.venue_id'], name=op.f('fk_quote__venue_id__venue'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('quote_id', name=op.f('pk_quote')),
    sa.UniqueConstraint('instrument_id', 'venue_id', name='uq_quote_instrument_id_venue_id'),
    schema='master'
    )
    op.create_index('idx_quote_instrument_id', 'quote', ['instrument_id'], unique=False, schema='master')
    op.create_index('idx_quote_instrument_id_is_primary', 'quote', ['instrument_id'], unique=False, schema='master', postgresql_where=sa.text('is_primary = true'))
    op.create_index('idx_quote_is_primary', 'quote', ['is_primary'], unique=False, schema='master')
    op.create_index('idx_quote_mic', 'quote', ['mic'], unique=False, schema='master')
    op.create_index('idx_quote_ric', 'quote', ['ric'], unique=False, schema='master')
    op.create_index('idx_quote_ticker', 'quote', ['ticker'], unique=False, schema='master')
    op.create_table('std_financial_filing',
    sa.Column('std_financial_filing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_type_id', sa.Integer(), nullable=False),
    sa.Column('reported_currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('converted_currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('calendar_end_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_month', sa.SmallInteger(), nullable=True),
    sa.Column('is_interim', sa.Boolean(), nullable=True),
    sa.Column('is_hybrid', sa.Boolean(), nullable=True),
    sa.Column('filing_end_date', sa.Date(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('reported_unit', sa.String(length=10), nullable=True),
    sa.Column('converted_unit', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['master.company.company_id'], name=op.f('fk_std_financial_filing__company_id__company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['converted_currency_id'], ['master.currency.currency_id'], name=op.f('fk_std_financial_filing__converted_currency_id__currency'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_type_id'], ['master.financial_period_type.financial_period_type_id'], name=op.f('fk_std_financial_filing__period_type_id__financial_period_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reported_currency_id'], ['master.currency.currency_id'], name=op.f('fk_std_financial_filing__reported_currency_id__currency'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('std_financial_filing_id', name=op.f('pk_std_financial_filing')),
    sa.UniqueConstraint('company_id', 'period_end_date', 'filing_end_date', 'period_type_id', name='uq_std_financial_filing_company_period'),
    schema='master'
    )
    op.create_index('idx_std_financial_filing_company_id', 'std_financial_filing', ['company_id'], unique=False, schema='master')
    op.create_index('idx_std_financial_filing_filing_end_date', 'std_financial_filing', ['filing_end_date'], unique=False, schema='master')
    op.create_index('idx_std_financial_filing_period_end_date', 'std_financial_filing', ['period_end_date'], unique=False, schema='master')
    op.create_table('corpact_adjustment',
    sa.Column('equity_id', sa.BigInteger(), nullable=False),
    sa.Column('adj_date', sa.Date(), nullable=False),
    sa.Column('adj_type', sa.SmallInteger(), nullable=False),
    sa.Column('end_adj_date', sa.Date(), nullable=True),
    sa.Column('adj_factor', sa.Double(), nullable=False),
    sa.Column('cum_adj_factor', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['adj_type'], ['master.corpact_type.corpact_type_id'], name=op.f('fk_corpact_adjustment__adj_type__corpact_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equity_id'], ['master.equity.equity_id'], name=op.f('fk_corpact_adjustment__equity_id__equity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equity_id', 'adj_date', 'adj_type', name=op.f('pk_corpact_adjustment')),
    schema='master'
    )
    op.create_index('idx_corpact_adjustment_equity_id_adj_date_end_adj_date', 'corpact_adjustment', ['equity_id', 'adj_date', 'end_adj_date'], unique=False, schema='master')
    op.create_table('corpact_event',
    sa.Column('corpact_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('equity_id', sa.Integer(), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('corpact_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('res_equity_id', sa.Integer(), nullable=True),
    sa.Column('new_shares_count', sa.Double(), nullable=True),
    sa.Column('old_shares_count', sa.Double(), nullable=True),
    sa.Column('currency_id', sa.SmallInteger(), nullable=True),
    sa.Column('cash_amount', sa.Double(), nullable=True),
    sa.Column('offer_company_name', sa.String(length=255), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['corpact_type_id'], ['master.corpact_type.corpact_type_id'], name=op.f('fk_corpact_event__corpact_type_id__corpact_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['master.currency.currency_id'], name=op.f('fk_corpact_event__currency_id__currency'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equity_id'], ['master.equity.equity_id'], name=op.f('fk_corpact_event__equity_id__equity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['res_equity_id'], ['master.equity.equity_id'], name=op.f('fk_corpact_event__res_equity_id__equity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('corpact_event_id', name=op.f('pk_corpact_event')),
    sa.UniqueConstraint('equity_id', 'event_sequence', 'corpact_type_id', 'effective_date', name='uq_corpact_event_natural_key'),
    schema='master'
    )
    op.create_index('idx_corpact_event_corpact_type_id', 'corpact_event', ['corpact_type_id'], unique=False, schema='master')
    op.create_index('idx_corpact_event_effective_date', 'corpact_event', ['effective_date'], unique=False, schema='master')
    op.create_index('idx_corpact_event_equity_id', 'corpact_event', ['equity_id'], unique=False, schema='master')
    op.create_index('idx_corpact_event_equity_id_event_sequence', 'corpact_event', ['equity_id', 'event_sequence'], unique=False, schema='master')
    op.create_table('dividend',
    sa.Column('dividend_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('equity_id', sa.Integer(), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('dividend_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('dividend_rate', sa.Double(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('is_pay_date_estimated', sa.Boolean(), nullable=True),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_effective_date_estimated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['master.currency.currency_id'], name=op.f('fk_dividend__currency_id__currency'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dividend_type_id'], ['master.dividend_type.dividend_type_id'], name=op.f('fk_dividend__dividend_type_id__dividend_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equity_id'], ['master.equity.equity_id'], name=op.f('fk_dividend__equity_id__equity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dividend_id', name=op.f('pk_dividend')),
    sa.UniqueConstraint('equity_id', 'event_sequence', name='uq_dividend_natural_key'),
    schema='master'
    )
    op.create_index('idx_dividend_currency_id', 'dividend', ['currency_id'], unique=False, schema='master')
    op.create_index('idx_dividend_dividend_type_id', 'dividend', ['dividend_type_id'], unique=False, schema='master')
    op.create_index('idx_dividend_equity_id_effective_date', 'dividend', ['equity_id', 'effective_date'], unique=False, schema='master')
    op.create_table('dividend_adjustment',
    sa.Column('equity_id', sa.BigInteger(), nullable=False),
    sa.Column('ex_div_date', sa.Date(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Double(), nullable=False),
    sa.Column('price_currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('total_div_converted', sa.Double(), nullable=False),
    sa.Column('div_adj_factor', sa.Double(), nullable=False),
    sa.Column('cum_div_factor', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['equity_id'], ['master.equity.equity_id'], name=op.f('fk_dividend_adjustment__equity_id__equity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_currency_id'], ['master.currency.currency_id'], name=op.f('fk_dividend_adjustment__price_currency_id__currency'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('equity_id', 'ex_div_date', name=op.f('pk_dividend_adjustment')),
    sa.UniqueConstraint('equity_id', 'ex_div_date', name='uq_dividend_adjustment_equity_id_ex_div_date'),
    schema='master'
    )
    op.create_table('market_data',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Double(), nullable=True),
    sa.Column('high', sa.Double(), nullable=True),
    sa.Column('low', sa.Double(), nullable=True),
    sa.Column('close', sa.Double(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('bid', sa.Double(), nullable=True),
    sa.Column('ask', sa.Double(), nullable=True),
    sa.Column('vwap', sa.Double(), nullable=True),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['master.currency.currency_id'], name=op.f('fk_market_data__currency_id__currency'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['master.quote.quote_id'], name=op.f('fk_market_data__quote_id__quote'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_date', 'quote_id', name=op.f('pk_market_data')),
    schema='master'
    )
    op.create_index('idx_market_data_quote_id_trade_date', 'market_data', ['quote_id', sa.literal_column('trade_date DESC')], unique=False, schema='master')
    op.create_index('idx_market_data_quote_id_trade_date_notnull', 'market_data', ['quote_id', sa.literal_column('trade_date DESC')], unique=False, schema='master', postgresql_where=sa.text('close IS NOT NULL'))
    op.create_index('idx_market_data_trade_date', 'market_data', ['trade_date'], unique=False, schema='master')
    op.create_table('total_return',
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['master.quote.quote_id'], name=op.f('fk_total_return__quote_id__quote'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('value_date', 'quote_id', name=op.f('pk_total_return')),
    schema='master'
    )
    op.create_index('idx_total_return_quote_id_value_date', 'total_return', ['quote_id', sa.literal_column('value_date DESC')], unique=False, schema='master')
    op.create_index('idx_total_return_value_date', 'total_return', ['value_date'], unique=False, schema='master')
    op.create_table('quote_mapping',
    sa.Column('internal_quote_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.SmallInteger(), nullable=False),
    sa.Column('external_quote_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['master.data_source.data_source_id'], name=op.f('fk_quote_mapping__data_source_id__data_source'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_quote_id'], ['master.quote.quote_id'], name=op.f('fk_quote_mapping__internal_quote_id__quote'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('internal_quote_id', name=op.f('pk_quote_mapping')),
    sa.UniqueConstraint('data_source_id', 'external_quote_id', name='uq_quote_mapping_source_ext'),
    schema='master'
    )
    op.create_table('share_outstanding',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity_id', sa.BigInteger(), nullable=False),
    sa.Column('number_of_shares', sa.BigInteger(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equity_id'], ['master.equity.equity_id'], name=op.f('fk_share_outstanding__equity_id__equity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date', 'equity_id', name='pk_share_outstanding'),
    schema='master'
    )
    op.create_index('idx_share_outstanding_equity_id_date', 'share_outstanding', ['equity_id', 'date'], unique=False, schema='master')
    op.create_table('std_financial_statement',
    sa.Column('std_financial_statement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('std_financial_filing_id', sa.Integer(), nullable=False),
    sa.Column('statement_type_id', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_consolidated', sa.Boolean(), nullable=False),
    sa.Column('public_date', sa.Date(), nullable=True),
    sa.Column('last_update_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['statement_type_id'], ['master.financial_statement_type.financial_statement_type_id'], name=op.f('fk_std_financial_statement__statement_type_id__financial_statement_type')),
    sa.ForeignKeyConstraint(['std_financial_filing_id'], ['master.std_financial_filing.std_financial_filing_id'], name=op.f('fk_std_financial_statement__std_financial_filing_id__std_financial_filing'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('std_financial_statement_id', name=op.f('pk_std_financial_statement')),
    sa.UniqueConstraint('std_financial_filing_id', 'statement_type_id', name='uq_std_financial_statement_filing_id_statement_type_id'),
    schema='master'
    )
    op.create_index('idx_std_financial_statement_statement_type_id', 'std_financial_statement', ['statement_type_id'], unique=False, schema='master')
    op.create_index('idx_std_financial_statement_std_financial_filing_id', 'std_financial_statement', ['std_financial_filing_id'], unique=False, schema='master')
    op.create_table('std_financial_value',
    sa.Column('std_financial_statement_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_type_id', sa.Integer(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('filing_end_date', sa.Date(), nullable=False),
    sa.Column('statement_type_id', sa.Integer(), nullable=False),
    sa.Column('std_financial_item_id', sa.Integer(), nullable=False),
    sa.Column('calendar_end_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('loaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['master.company.company_id'], name=op.f('fk_std_financial_value__company_id__company')),
    sa.ForeignKeyConstraint(['period_type_id'], ['master.financial_period_type.financial_period_type_id'], name=op.f('fk_std_financial_value__period_type_id__financial_period_type')),
    sa.ForeignKeyConstraint(['statement_type_id'], ['master.financial_statement_type.financial_statement_type_id'], name=op.f('fk_std_financial_value__statement_type_id__financial_statement_type')),
    sa.ForeignKeyConstraint(['std_financial_item_id'], ['master.std_financial_item.std_financial_item_id'], name=op.f('fk_std_financial_value__std_financial_item_id__std_financial_item')),
    sa.ForeignKeyConstraint(['std_financial_statement_id'], ['master.std_financial_statement.std_financial_statement_id'], name=op.f('fk_std_financial_value__std_financial_statement_id__std_financial_statement'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('std_financial_statement_id', 'std_financial_item_id', name='pk_std_financial_value'),
    sa.UniqueConstraint('company_id', 'period_type_id', 'period_end_date', 'filing_end_date', 'statement_type_id', 'std_financial_item_id', name='uq_std_financial_value_natural_key'),
    schema='master'
    )
    op.create_index('idx_std_financial_value_company_id_item_id_calendar_end_date', 'std_financial_value', ['company_id', 'std_financial_item_id', 'calendar_end_date'], unique=False, schema='master')
    op.create_index('idx_std_financial_value_item_id_calendar_end_date', 'std_financial_value', ['std_financial_item_id', 'calendar_end_date'], unique=False, schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_std_financial_value_item_id_calendar_end_date', table_name='std_financial_value', schema='master')
    op.drop_index('idx_std_financial_value_company_id_item_id_calendar_end_date', table_name='std_financial_value', schema='master')
    op.drop_table('std_financial_value', schema='master')
    op.drop_index('idx_std_financial_statement_std_financial_filing_id', table_name='std_financial_statement', schema='master')
    op.drop_index('idx_std_financial_statement_statement_type_id', table_name='std_financial_statement', schema='master')
    op.drop_table('std_financial_statement', schema='master')
    op.drop_index('idx_share_outstanding_equity_id_date', table_name='share_outstanding', schema='master')
    op.drop_table('share_outstanding', schema='master')
    op.drop_table('quote_mapping', schema='master')
    op.drop_index('idx_market_data_trade_date', table_name='market_data', schema='master')
    op.drop_index('idx_market_data_quote_id_trade_date_notnull', table_name='market_data', schema='master', postgresql_where=sa.text('close IS NOT NULL'))
    op.drop_index('idx_market_data_quote_id_trade_date', table_name='market_data', schema='master')
    op.drop_table('market_data', schema='master')
    op.drop_table('dividend_adjustment', schema='master')
    op.drop_index('idx_dividend_equity_id_effective_date', table_name='dividend', schema='master')
    op.drop_index('idx_dividend_dividend_type_id', table_name='dividend', schema='master')
    op.drop_index('idx_dividend_currency_id', table_name='dividend', schema='master')
    op.drop_table('dividend', schema='master')
    op.drop_index('idx_corpact_event_equity_id_event_sequence', table_name='corpact_event', schema='master')
    op.drop_index('idx_corpact_event_equity_id', table_name='corpact_event', schema='master')
    op.drop_index('idx_corpact_event_effective_date', table_name='corpact_event', schema='master')
    op.drop_index('idx_corpact_event_corpact_type_id', table_name='corpact_event', schema='master')
    op.drop_table('corpact_event', schema='master')
    op.drop_index('idx_corpact_adjustment_equity_id_adj_date_end_adj_date', table_name='corpact_adjustment', schema='master')
    op.drop_table('corpact_adjustment', schema='master')
    op.drop_index('idx_std_financial_filing_period_end_date', table_name='std_financial_filing', schema='master')
    op.drop_index('idx_std_financial_filing_filing_end_date', table_name='std_financial_filing', schema='master')
    op.drop_index('idx_std_financial_filing_company_id', table_name='std_financial_filing', schema='master')
    op.drop_table('std_financial_filing', schema='master')
    op.drop_index('idx_quote_ticker', table_name='quote', schema='master')
    op.drop_index('idx_quote_ric', table_name='quote', schema='master')
    op.drop_index('idx_quote_mic', table_name='quote', schema='master')
    op.drop_index('idx_quote_is_primary', table_name='quote', schema='master')
    op.drop_index('idx_quote_instrument_id_is_primary', table_name='quote', schema='master', postgresql_where=sa.text('is_primary = true'))
    op.drop_index('idx_quote_instrument_id', table_name='quote', schema='master')
    op.drop_table('quote', schema='master')
    op.drop_index('idx_instrument_mapping_ext_id_ds_id_type_id', table_name='instrument_mapping', schema='master')
    op.drop_table('instrument_mapping', schema='master')
    op.drop_index('idx_equity_type_id', table_name='equity', schema='master')
    op.drop_index('idx_equity_ticker', table_name='equity', schema='master')
    op.drop_index('idx_equity_sedol', table_name='equity', schema='master')
    op.drop_index('idx_equity_ric', table_name='equity', schema='master')
    op.drop_index('idx_equity_isin', table_name='equity', schema='master')
    op.drop_index('idx_equity_cusip', table_name='equity', schema='master')
    op.drop_table('equity', schema='master')
    op.drop_table('entity_classification', schema='master')
    op.drop_table('company_weblink', schema='master')
    op.drop_index('idx_company_market_cap_loaded_at', table_name='company_market_cap', schema='master')
    op.drop_index('idx_company_market_cap_date', table_name='company_market_cap', schema='master')
    op.drop_index('idx_company_market_cap_company_date', table_name='company_market_cap', schema='master')
    op.drop_table('company_market_cap', schema='master')
    op.drop_index('idx_venue_mapping_ext_id_ds_id_type_id', table_name='venue_mapping', schema='master')
    op.drop_table('venue_mapping', schema='master')
    op.drop_index('idx_std_financial_item_mapping_external_item_id_data_source_id', table_name='std_financial_item_mapping', schema='master')
    op.drop_table('std_financial_item_mapping', schema='master')
    op.drop_index('idx_instrument_type_id', table_name='instrument', schema='master')
    op.drop_index('idx_instrument_symbol', table_name='instrument', schema='master')
    op.drop_index('idx_instrument_entity_id', table_name='instrument', schema='master')
    op.drop_table('instrument', schema='master')
    op.drop_index('idx_entity_mapping_ext_id_ds_id_type_id', table_name='entity_mapping', schema='master')
    op.drop_table('entity_mapping', schema='master')
    op.drop_table('company', schema='master')
    op.drop_index('idx_classification_node_scheme_id_parent_code', table_name='classification_node', schema='master')
    op.drop_index('idx_classification_node_scheme_id_level_number', table_name='classification_node', schema='master')
    op.drop_table('classification_node', schema='master')
    op.drop_table('venue', schema='master')
    op.drop_index('idx_std_financial_item_name', table_name='std_financial_item', schema='master')
    op.drop_table('std_financial_item', schema='master')
    op.drop_index('idx_fx_rate_rate_date', table_name='fx_rate', schema='master')
    op.drop_index('idx_fx_rate_loaded_at', table_name='fx_rate', schema='master')
    op.drop_index('idx_fx_rate_currencies_rate_date', table_name='fx_rate', schema='master')
    op.drop_index('idx_fx_rate_base_currency_id_rate_date', table_name='fx_rate', schema='master')
    op.drop_index('idx_fx_rate_base_currency_id_quote_currency_id', table_name='fx_rate', schema='master')
    op.drop_table('fx_rate', schema='master')
    op.drop_index('idx_entity_type_id', table_name='entity', schema='master')
    op.drop_index('idx_entity_name', table_name='entity', schema='master')
    op.drop_table('entity', schema='master')
    op.drop_index('idx_currency_pair_quote', table_name='currency_pair', schema='master')
    op.drop_index('idx_currency_pair_base', table_name='currency_pair', schema='master')
    op.drop_table('currency_pair', schema='master')
    op.drop_table('country_region', schema='master')
    op.drop_table('classification_level', schema='master')
    op.drop_table('weblink_type', schema='master')
    op.drop_table('venue_type', schema='master')
    op.drop_index('idx_std_financial_value_load_time', table_name='std_financial_value_load', schema='master')
    op.drop_table('std_financial_value_load', schema='master')
    op.drop_table('region', schema='master')
    op.drop_index('idx_market_data_load_time', table_name='market_data_load', schema='master')
    op.drop_table('market_data_load', schema='master')
    op.drop_table('instrument_type', schema='master')
    op.drop_table('financial_statement_type', schema='master')
    op.drop_table('financial_period_type', schema='master')
    op.drop_table('equity_type', schema='master')
    op.drop_table('entity_type', schema='master')
    op.drop_table('dividend_type', schema='master')
    op.drop_table('data_source', schema='master')
    op.drop_table('currency', schema='master')
    op.drop_table('country', schema='master')
    op.drop_table('corpact_type', schema='master')
    op.drop_index('idx_company_market_cap_load_time', table_name='company_market_cap_load', schema='master')
    op.drop_table('company_market_cap_load', schema='master')
    op.drop_table('classification_scheme', schema='master')
    # ### end Alembic commands ###
